services:
  site:
    build: ./site
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./site:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  celery:
    build: ./site
    command: celery --app=config worker
    volumes:
      - ./site:/app
    depends_on:
      - site
      - redis
    env_file:
      - .env

  redis:
    image: redis:8.2-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data

  broker:
    image: rabbitmq:4.1.3-management
    restart: unless-stopped
    hostname: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  rabbitmqdata:
  redisdata: