# Generated by Django 5.2.5 on 2025-08-19 08:38

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersyncbroker',
            managers=[
                ('objects', api.models.ManagerSyncBroker()),
            ],
        ),
    ]
